version: "3"
services:
  master_node:
    image: replicated-logs-app
    build: .
    container_name: master_node
    command: 'uvicorn app.run_master:app --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000

  secondary_node_1:
    container_name: secondary_node_1
    image: replicated-logs-app
    command: 'uvicorn app.run_secondary:app --host 0.0.0.0 --port 8001'
    depends_on:
      - master_node
    expose:
      - 8001

  secondary_node_2:
    container_name: secondary_node_2
    image: replicated-logs-app
    command: 'uvicorn app.run_secondary:app --host 0.0.0.0 --port 8002'
    depends_on:
      - master_node
    expose:
      - 8002
